export const data = [
    {
        name: "Big and Juicy Wagyu Beef Cheeseburger",
        topMenu: "Wagyu Beef Cheeseburger",
        description:
            "Burger daging wagyu juicy dengan keju leleh, cocok untuk cemilan sore.",
        category: "Snack",
        campus: 1,
        image: "/test/images/1.png",
        address: "UNESA 1",
        rating: 4.9,
        review: [5, 5, 5],
    },
    {
        name: "Fresh Lime Roasted Salmon with Ginger Sauce",
        topMenu: "Roasted Salmon",
        description:
            "Salmon panggang segar dengan saus jahe yang nikmat dan menyegarkan.",
        category: "Lunch",
        campus: 2,
        image: "/test/images/2.png",
        address: "UNESA 2",
        rating: 4.9,
        review: [5, 5, 5, 5, 5],
    },
    {
        name: "Strawberry Oatmeal Pancake with Honey Syrup",
        topMenu: "Oatmeal Pancake",
        description:
            "Pancake oatmeal dengan sirup madu dan topping stroberi segar.",
        category: "Breakfast",
        campus: 1,
        image: "/test/images/3.png",
        address: "UNESA 1",
        rating: 4.9,
        review: [5, 4, 5],
    },
    {
        name: "Fresh and Healthy Mixed Mayonnaise Salad",
        topMenu: "Mayonnaise Salad",
        description:
            "Salad sehat dan segar dengan saus mayones dan protein nabati.",
        category: "Breakfast",
        campus: 1,
        image: "/test/images/4.png",
        address: "UNESA 1",
        rating: 4.9,
        review: [5, 4, 5],
    },
    {
        name: "Chicken Meatballs with Cream Cheese",
        topMenu: "Meatballs with Cheese",
        description:
            "Bola-bola ayam gurih dengan saus keju lembut yang meleleh di mulut.",
        category: "Snack",
        campus: 2,
        image: "/test/images/5.png",
        address: "UNESA 2",
        rating: 4.9,
        review: [5, 5, 5],
    },
    {
        name: "Chicken Punch with King Chile",
        topMenu: "Spicy Chicken Punch",
        description:
            "Ayam sambal pedas khas dengan nasi putih dan sayur segar.",
        category: "Snack",
        campus: 1,
        image: "/test/images/6.png",
        address: "UNESA 1",
        rating: 4.9,
        review: [5, 5, 4, 5, 5],
    },
    {
        name: "Fruity Pancake with Orange & Blueberry",
        topMenu: "Orange & Blueberry Pancake",
        description:
            "Pancake buah dengan rasa jeruk dan blueberry segar, cocok untuk sarapan.",
        category: "Breakfast",
        campus: 1,
        image: "/test/images/7.png",
        address: "UNESA 1",
        rating: 4.9,
        review: [5, 4, 5],
    },
    {
        name: "The Best Easy One Pot Chicken and Rice",
        topMenu: "Chicken and Rice",
        description: "Nasi ayam dalam satu panci, praktis dan bergizi.",
        category: "Snack",
        campus: 1,
        image: "/test/images/8.png",
        address: "UNESA 1",
        rating: 4.9,
        review: [5, 5, 5],
    },
    {
        name: "The Creamiest Creamy Chicken and Bacon Pasta",
        topMenu: "Chicken and Bacon Pasta",
        description: "Pasta krim dengan potongan ayam dan bacon gurih.",
        category: "Lunch",
        campus: 1,
        image: "/test/images/9.png",
        address: "UNESA 1",
        rating: 4.9,
        review: [5, 4, 5],
    },
];
